# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CommaSeparatedIntegerField(max_length=200)),
                ('code', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=2000)),
                ('scientific_question', models.CharField(max_length=500)),
                ('main_text', models.CharField(max_length=200000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
